### ISSUE TITLE
cannot read status of undefined 

### ISSUE THREAD

**Issue by daninko** [mugi-uno/parcel-plugin-bundle-manifest#2]
Ran into this issue after installing the parcel-plugin-bundle-manifest plugin and running the parcel command on the file I wanted to watch. I double checked to make sure that the path to the file that I wanted parcel to watch was correct. Have the plugin installed as a dev dependency for my project.

`🚨  Cannot read property 'status' of undefined
    at readManifestJson (/node_modules/parcel-plugin-bundle-manifest/plugins/BundleManifestPlugin.js:15:13)
    at Bundler.bundler.on (/node_modules/parcel-plugin-bundle-manifest/plugins/BundleManifestPlugin.js:50:27)
    at emitOne (events.js:96:13)
    at Bundler.emit (events.js:191:7)
    at /usr/local/lib/node_modules/parcel-bundler/lib/Bundler.js:236:16
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/parcel-bundler/lib/Bundler.js:5:191)
    at /usr/local/lib/node_modules/parcel-bundler/lib/Bundler.js:5:361
    at process._tickCallback (internal/process/next_tick.js:109:7)`

**Comment by daninko** [comment]
I found when I removed all instances of `logger.status()` from plugins/BundleManifestPlugin.js code worked as expected.

**Comment by shakyShane** [comment]
Same here.

**Comment by hi-zhaolei** [comment]
The parcel bundler instance does not have a logger attribute in new version. 
<img width="773" alt="2018-03-26 9 13 31" src="https://user-images.githubusercontent.com/5736062/37908373-9d122d8c-313a-11e8-8e02-f3b0831de55d.png">

**Comment by mugi-uno** [comment]
fix by #3.
thx @xcambar.
