### ISSUE TITLE
Cannot find module 'parcel-bundler/src/Logger'

### ISSUE THREAD

**Issue by dobesv** [mugi-uno/parcel-plugin-bundle-manifest#4]
Getting this error after installing this plugin:

```
⚠️  Cannot find module 'parcel-bundler/src/Logger'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (/home/ubuntu/.config/yarn/global/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/ubuntu/vaultdropweb/node_modules/parcel-plugin-bundle-manifest/plugins/BundleManifestPlugin.js:4:16)
    at Module._compile (/home/ubuntu/.config/yarn/global/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by dobesv** [comment]
Ah, this is because I ran parcel using `npx`, so it wasn't installed into `node_modules`
