### ISSUE TITLE
Error when bundle has no assets

### ISSUE THREAD

**Issue by dobesv** [mugi-uno/parcel-plugin-bundle-manifest#5]
For whatever reason there is a bundle with no assets.  The manifest builder fails with an error.

```
Bundle {
  type: 'map',
  name: '/home/ubuntu/vaultdropweb/app/roovy/static/gen/core.1dcb4b5b.map',
  parentBundle: 
   Bundle {
     type: 'css',
     name: '/home/ubuntu/vaultdropweb/app/roovy/static/gen/core.1dcb4b5b.css',
     parentBundle: 
      Bundle {
        type: 'css',
        name: '/home/ubuntu/vaultdropweb/app/roovy/static/gen/vendor.3671c711.css',
        parentBundle: [Bundle],
        entryAsset: [SASSAsset],
        assets: [Set],
        childBundles: [Set],
        siblingBundles: [Set],
        siblingBundlesMap: [Map],
        offsets: Map {},
        totalSize: 109,
        bundleTime: 5037 },
     entryAsset: 
      CSSAsset {
        id: 299,
        name: '/home/ubuntu/vaultdropweb/node_modules/jquery-ui/themes/base/core.css',
        basename: 'core.css',
        relativeName: '../../../../node_modules/jquery-ui/themes/base/core.css',
        package: [Object],
        options: [Object],
        encoding: 'utf8',
        type: 'css',
        processed: true,
        contents: null,
        ast: null,
        generated: [Object],
        hash: '45a7b2956ddf6cad37d8febd559e6c1d',
        parentDeps: [Set],
        dependencies: [Map],
        depAssets: [Map],
        parentBundle: [Circular],
        bundles: [Set],
        cacheData: {},
        buildTime: 1772,
        bundledSize: 2663 },
     assets: Set { [CSSAsset] },
     childBundles: Set { [Bundle], [Circular] },
     siblingBundles: Set { [Bundle], [Circular] },
     siblingBundlesMap: Map { 'js' => [Bundle], 'map' => [Circular] },
     offsets: Map {},
     totalSize: 1574,
     bundleTime: 1804 },
  entryAsset: null,
  assets: Set {},
  childBundles: Set {},
  siblingBundles: Set {},
  siblingBundlesMap: Map {},
  offsets: Map {},
  totalSize: 0,
  bundleTime: 0 }
🚨  Cannot read property 'basename' of undefined
    at feedManifestValue (/home/ubuntu/vaultdropweb/node_modules/parcel-plugin-bundle-manifest/plugins/BundleManifestPlugin.js:39:101)
    at /home/ubuntu/vaultdropweb/node_modules/parcel-plugin-bundle-manifest/plugins/BundleManifestPlugin.js:43:7
    at Set.forEach (<anonymous>)
    at feedManifestValue (/home/ubuntu/vaultdropweb/node_modules/parcel-plugin-bundle-manifest/plugins/BundleManifestPlugin.js:42:25)
    at /home/ubuntu/vaultdropweb/node_modules/parcel-plugin-bundle-manifest/plugins/BundleManifestPlugin.js:43:7
    at Set.forEach (<anonymous>)
    at feedManifestValue (/home/ubuntu/vaultdropweb/node_modules/parcel-plugin-bundle-manifest/plugins/BundleManifestPlugin.js:42:25)
    at /home/ubuntu/vaultdropweb/node_modules/parcel-plugin-bundle-manifest/plugins/BundleManifestPlugin.js:43:7
    at Set.forEach (<anonymous>)
    at feedManifestValue (/home/ubuntu/vaultdropweb/node_modules/parcel-plugin-bundle-manifest/plugins/BundleManifestPlugin.js:42:25)

```

**Comment by dobesv** [comment]
I added an empty check locally, it seems to work:

```
      let input = bundle.entryAsset ? bundle.entryAsset.basename : bundle.assets.size ? bundle.assets.values().next().value.basename : null;
      if(input) {
          manifestValue[input] = output;
          logger.status('✓', `  bundle : ${input} => ${output}`);
      }

```

**Comment by dobesv** [comment]
Reproduction: https://github.com/dobesv/parcel-manifest-bug
